### ISSUE TITLE
threading.Thread.isAlive is removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [cdent/paste#39]
`isAlive` was deprecated and removed in Python 3.9 with https://github.com/python/cpython/pull/15225 . Use `is_alive` for Python 3.9 compatibility. I will raise a PR for this.

```
python -m paste.httpserver
serving on http://127.0.0.1:8888
^C
/home/xtreak/anaconda3/envs/nose2-venv/lib/python3.8/site-packages/paste/httpserver.py:955: DeprecationWarning: isAlive() is deprecated, use is_alive() instead
  if worker.isAlive():
```

**Comment by cdent** [comment]
Thanks for raising this and offering to provide a fix.

As you've probably read elsewhere in the repo: my efforts here are to keep paste only on life support, and not much more, so that people will stop using it. But as people are willing to provide fixes, I'm happy to merge them and keep on doing some releases.
